print("Bartek Słodyczyka")
print('o----')
print(' ||||')
print('*' * 10)
print('  *')
print(' * *')
print('*   *')
print('*   *')
print(' * *')
print('  *')
print('  M')
print("| '   e")
print('  W  W')
